[[headers]]
  for = "/target/artifacts/693de2cd-ac92-d2c7-59fc-a3c0f2bce646/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/target/artifacts/be92ac4c-e72f-9f82-2a80-2c211ea86578/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/target/artifacts/bf77db72-3ab6-64ce-3bc5-6208be2f09c1/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/target/artifacts/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/target/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/css/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/js/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/target/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/heavy.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/lean.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.eot"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"
